### ISSUE TITLE
Daily total not acting as expected

### ISSUE THREAD

**Issue by sarahspins** [loudnate/Loop#140]
I think this stopped working with the 0.10.1 update.... two screenshots from two different nights show the same issue. @CrushingT1D is seeing similar, and suspects it's a reset bug (every 5 minutes with each new MySentry vs daily) combined with a decimal place bug.

![img_0276](https://cloud.githubusercontent.com/assets/16582717/18078203/f0a4655a-6e4f-11e6-9d7f-6773891fcb45.PNG)

![img_0286](https://cloud.githubusercontent.com/assets/16582717/18078202/f0a10a2c-6e4f-11e6-99bb-fcbe8fec5e8b.PNG)

**Comment by CrushingT1D** [comment]
I confirmed the same issue on my end with 0.10

**Comment by CrushingT1D** [comment]
I am pretty sure it is over in LoopKit in this set of changes https://github.com/loudnate/LoopKit/commit/7cfac7b075ccfef72c608a646242b93f21d8c43b or at a minimum somewhere in this list https://github.com/loudnate/LoopKit/commits/master/InsulinKit/UI/InsulinDeliveryTableViewController.swift

My guess is that it is displaying the total since the last reading instead of the total from the whole day. It also seems to be displaying a fraction of units, but that may just be a product of display layer.

Let us know if we should actually move the Issue over there or if this is sufficient.

**Comment by CrushingT1D** [comment]
One user is saying that they are not having the issue on 0.10.
They also seem to have the PM cut off from a screen sizing cut off on 5s (could fix both at once)

**Comment by jlucasvt** [comment]
My observations on this, are that the 24hr math is correct, however the 24hr date that is displayed is incorrect.  The date should be "since 12:00 or 12:01" or there abouts but instead the information is displaying the last subtractive reservoir event date.

**Comment by CrushingT1D** [comment]
duplicate with https://github.com/loudnate/Loop/issues/140
