### ISSUE TITLE
Failed bolus

### ISSUE THREAD

**Issue by eyim** [loudnate/Loop#52]
Tried to bolus through the app.  It says it failed.  Then tried it again and it went through.  The bolus insulin on board correctly shows the right amount but it never showed up in the Nightscout upload.  

The problem is that the projected bg levels don't show the impact of that bolus even though it shows 10+ units of insulin on board.  His bg projection goes right up to 700.

**Comment by eyim** [comment]
Hmm looks like the issue is that on the main page it says bolus iob is 12 units which is correct but when you click on the insulin graph.  It says only 4.4 iob.  It hasn't been low temping because I turned it off and there is no way that removing the basal can cut the iob by 8 units

**Comment by loudnate** [comment]
Can you show me the reservoir readings? (Tap on the IOB graph)

**Comment by eyim** [comment]
https://www.dropbox.com/sc/6avvi5irudbzm51/AADaML0btZaCTpvHMyPP_mq7a

Here are 4 screenshots of the main screen plus the reservoir readings.  The one at 6:54 pm is the one I think is missing from the iob calculation

**Comment by loudnate** [comment]
What is the calculated IOB value?

There are large chunks of data missing in that reservoir history, as well as a rewind/prime. According to your pump history, what time were the boluses delivered?

**Comment by eyim** [comment]
Bolus:
9:27 1 unit
8:59 4.5 units
8:15 2 units
6:54 11.5 units
5:03 4.05 units
4:32 2 units

Right now the pump says 11.3 units on board.  The home screen of the app says 11.475 units on board.  But when you click on the insulin graph it shows 8.14 now.

When I sent you the earlier screenshots, the main screen showed 12+ and the graph showed 4.4

We changed the reservoir around 8:50 or so because he has been high and we are changing everything out.

The issues started before we changed the reservior

**Comment by loudnate** [comment]
Here's your missing insulin:
<img width="302" alt="screen shot 2016-07-01 at 9 45 05 pm" src="https://cloud.githubusercontent.com/assets/212876/16538296/1b1eb370-3fd5-11e6-94ff-367364b96c6b.png">

So according to the max insulin delivery of 2.0 U/min, this drop was assumed to be false (e.g. a prime).

This is a bug in Loop which is exposed when the phone time and the pump time drift out-of-sync. With x23 pumps, I'm erroneously mixing pump clock (from sentry packets) with phone clock (manual reservoir readings before a bolus).

This was identified and fixed in #49, and I'll go ahead and cut this as a release.

So sorry you experienced this – thank you for finding it and filing. I'm going to close this as a duplicate as #49.

**Comment by eyim** [comment]
No problem. Glad to know it is a bug that already has a solution.  Thank you again for developing this implementation.  My son loves it and doesn't want to go back to the edison rig.
